pool:
  vmImage: 'windows-2019'

pr: none

trigger:
  batch: True
  branches:
    include:
    - master
  paths:
    exclude:
    - README.md
    - LICENSE

variables:
  BuildConfiguration: Release

# do this before all your .NET Core tasks
steps:
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: 'restore'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '**/*.csproj'
    arguments: '--configuration $(BuildConfiguration)' # Update this to match your need

- task: DotNetCoreCLI@2
  displayName: Publish
  inputs:
    command: publish
    projects: '**/*.csproj'
    publishWebProjects: false
    arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
    zipAfterPublish: True
    
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'